plugins {
    id("com.google.protobuf") version "0.9.4"
}

group = 'me.kasuki.kstaff'
version = '1.0-SNAPSHOT'

repositories {
    maven {
        url = 'https://jitpack.io'
    }

    maven {
        url = 'https://repo.aikar.co/content/groups/aikar/'
    }

    maven {
        url = 'https://repo.codemc.io/repository/maven-public/'
    }

    maven {
        url = 'https://maven.insidious.cc/repository/maven-mixed/'
    }

    mavenLocal()
    mavenCentral()
}

shadowJar {
    archiveBaseName.set('KStaff-API-1.0-SNAPSHOT')
    archiveClassifier.set('')
    archiveVersion.set('')
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.28.2'
    }
    generateProtoTasks {
        all().configureEach { task ->
            task.builtins {
                java {

                }
            }
        }
    }
}


dependencies {
    annotationProcessor('org.projectlombok:lombok:1.18.36')
    compileOnly('org.projectlombok:lombok:1.18.36')
    compileOnly('org.xerial:sqlite-jdbc:3.47.0.0')
    compileOnly('com.google.protobuf:protobuf-java:4.28.2')
    compileOnly('redis.clients:jedis:6.0.0')
    compileOnly('com.github.ben-manes.caffeine:caffeine:2.9.3')
}